-- Additional sales_sku_map entries so 2026 sales match Spring 2027 plan items.
-- Generated by token-similarity matching on normalized size + description
-- (>=0.60 Jaccard with a clear margin over the runner-up). Ambiguous and
-- genuinely-absent SKUs are deliberately NOT included — those need a human.
insert into sales_sku_map (sku, sales_desc, sales_size, plan_item_name, source, note)
values
  ('AN10HBGER013', 'GERANIUM WITH IVY DARK RED', '10" HB', 'HB 10" GERANIUM DARK RED', 'auto-match', 'similarity 0.75'),
  ('AN10HBGER015', 'GERANIUM WITH IVY DARK PINK', '10" HB', 'HB 10" GERANIUM DARK PINK', 'auto-match', 'similarity 0.75'),
  ('AN10HBGER014', 'GERANIUM WITH IVY SALMON', '10" HB', 'HB 10" GERANIUM SALMON', 'auto-match', 'similarity 0.67'),
  ('AN04IVY006', 'IVY HEDERA MARY BETH', '4.5" / 10 PACK', '4.5" IVY HEDERA MARY BETH', 'auto-match', 'similarity 1.00'),
  ('AN04VNC001', 'VINCA VINE ILLUMINATION', '4.5" / 10 PACK', '4.5" VINCA VINE ILLUMINATION', 'auto-match', 'similarity 1.00'),
  ('AN04IVY002', 'IVY HEDERA GLACIER', '4.5" / 10 PACK', '4.5" IVY HEDERA GLACIER', 'auto-match', 'similarity 1.00'),
  ('AN04IVY005', 'IVY HEDERA HARLEQUIN', '4.5" / 10 PACK', '4.5" IVY HARLEQUIN', 'auto-match', 'similarity 0.67'),
  ('AN04IVY003', 'IVY HEDERA GOLDCHILD', '4.5" / 10 PACK', '4.5" IVY HEDERA GOLDCHILD', 'auto-match', 'similarity 1.00'),
  ('AN04VNC003', 'VINCA VINE VARIEGATED', '4.5" / 10 PACK', '4.5" VINCA VINE VARIEGATED', 'auto-match', 'similarity 1.00'),
  ('AN04VNC002', 'VINCA VINE EXPOFLORA', '4.5" / 10 PACK', '4.5" VINCA VINE EXPOFLORA', 'auto-match', 'similarity 1.00'),
  ('AN04VNC004', 'VINCA VINE WOJO''S JEM', '4.5" / 10 PACK', '4.5" VINCA VINE WOJO''S JEM', 'auto-match', 'similarity 1.00'),
  ('AN04IVY004', 'IVY HEDERA GOLDEN INGE', '4.5" / 10 PACK', '4.5" IVY GOLDEN INGE', 'auto-match', 'similarity 0.75'),
  ('AN04IVY008', 'IVY HEDERA YELLOW RIPPLE', '4.5" / 10 PACK', '4.5" IVY HEDERA YELLOW RIPPLE', 'auto-match', 'similarity 1.00'),
  ('AN04IVY007', 'IVY HEDERA WHITE RIPPLE', '4.5" / 10 PACK', '4.5" IVY HEDERA WHITE RIPPLE', 'auto-match', 'similarity 1.00'),
  ('AN04GRA001', 'GRASS CAREX AMAZON MIST', '4.5" / 10 PACK', '4.5" GRASS CAREX AMAZON MIST', 'auto-match', 'similarity 1.00'),
  ('AN04IVY009', 'IVY MINI ESTER', '4.5" / 10 PACK', '4.5" IVY MINI ESTER', 'auto-match', 'similarity 1.00'),
  ('AN04IVY001', 'IVY ALGERIAN TROPICAL BLIZZARD', '4.5" / 10 PACK', '4.5" IVY ALGERIAN TROPICAL BLIZZARD', 'auto-match', 'similarity 1.00'),
  ('AN04GRA002', 'GRASS CAREX RED ROOSTER', '4.5" / 10 PACK', '4.5" GRASS CAREX RED ROOSTER', 'auto-match', 'similarity 1.00'),
  ('AN04MUH002', 'MUHLENBECKIA COMPLEXIS ''WIRE VINE''', '4.5" / 10 PACK', '4.5" MUHLENBECKIA WIRE VINE ''COINS''', 'auto-match', 'similarity 0.60')
on conflict (sku) do update set plan_item_name = excluded.plan_item_name, note = excluded.note;
