-- Enable RLS on public tables flagged by Supabase (rls_disabled_in_public).
-- Matches the app's existing model: anon-key access + permissive allow-all policy
-- (auth is app-level floor codes, not RLS). Clears the critical alert without breaking access.
alter table public.announcements enable row level security;
drop policy if exists "allow all announcements" on public.announcements;
create policy "allow all announcements" on public.announcements for all to public using (true) with check (true);
alter table public.brehob_items enable row level security;
drop policy if exists "allow all brehob_items" on public.brehob_items;
create policy "allow all brehob_items" on public.brehob_items for all to public using (true) with check (true);
alter table public.broker_change_actions enable row level security;
drop policy if exists "allow all broker_change_actions" on public.broker_change_actions;
create policy "allow all broker_change_actions" on public.broker_change_actions for all to public using (true) with check (true);
alter table public.broker_reports enable row level security;
drop policy if exists "allow all broker_reports" on public.broker_reports;
create policy "allow all broker_reports" on public.broker_reports for all to public using (true) with check (true);
alter table public.category_pricing enable row level security;
drop policy if exists "allow all category_pricing" on public.category_pricing;
create policy "allow all category_pricing" on public.category_pricing for all to public using (true) with check (true);
alter table public.crop_run_sequence enable row level security;
drop policy if exists "allow all crop_run_sequence" on public.crop_run_sequence;
create policy "allow all crop_run_sequence" on public.crop_run_sequence for all to public using (true) with check (true);
alter table public.crop_run_templates enable row level security;
drop policy if exists "allow all crop_run_templates" on public.crop_run_templates;
create policy "allow all crop_run_templates" on public.crop_run_templates for all to public using (true) with check (true);
alter table public.driver_availability enable row level security;
drop policy if exists "allow all driver_availability" on public.driver_availability;
create policy "allow all driver_availability" on public.driver_availability for all to public using (true) with check (true);
alter table public.driver_requests enable row level security;
drop policy if exists "allow all driver_requests" on public.driver_requests;
create policy "allow all driver_requests" on public.driver_requests for all to public using (true) with check (true);
alter table public.facility_equipment enable row level security;
drop policy if exists "allow all facility_equipment" on public.facility_equipment;
create policy "allow all facility_equipment" on public.facility_equipment for all to public using (true) with check (true);
alter table public.hr_messages enable row level security;
drop policy if exists "allow all hr_messages" on public.hr_messages;
create policy "allow all hr_messages" on public.hr_messages for all to public using (true) with check (true);
alter table public.maintenance_requests enable row level security;
drop policy if exists "allow all maintenance_requests" on public.maintenance_requests;
create policy "allow all maintenance_requests" on public.maintenance_requests for all to public using (true) with check (true);
alter table public.program_inputs enable row level security;
drop policy if exists "allow all program_inputs" on public.program_inputs;
create policy "allow all program_inputs" on public.program_inputs for all to public using (true) with check (true);
alter table public.receiving_lines enable row level security;
drop policy if exists "allow all receiving_lines" on public.receiving_lines;
create policy "allow all receiving_lines" on public.receiving_lines for all to public using (true) with check (true);
alter table public.receiving_orders enable row level security;
drop policy if exists "allow all receiving_orders" on public.receiving_orders;
create policy "allow all receiving_orders" on public.receiving_orders for all to public using (true) with check (true);
alter table public.shipping_routes enable row level security;
drop policy if exists "allow all shipping_routes" on public.shipping_routes;
create policy "allow all shipping_routes" on public.shipping_routes for all to public using (true) with check (true);
alter table public.vacation_requests enable row level security;
drop policy if exists "allow all vacation_requests" on public.vacation_requests;
create policy "allow all vacation_requests" on public.vacation_requests for all to public using (true) with check (true);
